//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace DataLayer
{
  
   
    public  class RoleMetaData
    {
        [Key]
        public int RoleId { get; set; }
        [DisplayName("عنوان نقش")]
        public string RoleTittle { get; set; }
        [DisplayName("عنوان سیستمی نقش")]
        public string RoleName { get; set; }
    }
}